apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cicd-demo
  template:
    metadata:
      labels:
        app: flask-cicd-demo
    spec:
      containers:
        - name: flask-cicd-demo
          image: mrunalini01/flask-cicd-demo:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-cicd-service
spec:
  type: NodePort
  selector:
    app: flask-cicd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
